FROM golang:1.23-alpine AS build
WORKDIR /src

# go.sum is generated by `go mod tidy`; copy it if present.
COPY go.mod ./
COPY go.sum* ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/helios ./cmd/helios

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/helios /helios

# helios reads its config from env (see internal/config). Persistent volume must
# be mounted at BACKLIGHT_DB_PATH parent and BACKLIGHT_OUTPUT_ROOT.
EXPOSE 8080
ENTRYPOINT ["/helios"]
